# This is a basic workflow to help you get started with Actions

name: Ansible nginx Pipeline

#on:
  # Triggers the workflow on push or pull request events but only for the main branch
#  push:
#    branches: [ main ]

on:
  push:
    branches:
      - 'main'
    # Triggers the workflow on push event but only for the *.yml files
    paths:
      - 'playbook/*.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-nginx"
  build-nginx:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Start Ansible Playbook
      - name: Start Ansible Playbook
        run: ansible-playbook -i inventory playbook/playbook.yml -K

      - name: Curl Website to see if it's running
        run: curl localhost:8080
        

      # Runs a set of commands using the runners shell
     # - name: Run a multi-line script
      #  run: |
       #   echo Add other actions to build,
        #  echo test, and deploy your project.